name: one_to_many

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor:
  sqlite3_flutter_libs:
  path_provider:
  path:

dev_dependencies:
  moor_generator:
  build_runner:

flutter:
  uses-material-design: true
